FROM rustlang/rust:nightly-alpine3.17
LABEL org.opencontainers.image.source="https://github.com/pesca-dev/docker-images"

# RUN rustup toolchain install nightly
# RUN rustup default nightly

RUN apk update && \
    apk add --no-cache bash binaryen gcc git g++ libc-dev make npm libressl-dev protobuf-dev protoc

RUN rustup target add wasm32-unknown-unknown

RUN cargo install cargo-leptos
RUN npm install -g sass

WORKDIR /work

CMD /bin/bash
